#!/usr/bin/env bash
# One-time setup on a fresh VPS (Ubuntu, run as root):
#
#   git clone https://github.com/uptonking/verges.git /opt/verges
#   cd /opt/verges
#   scripts/bootstrap.sh
#
# Preflight checks, interactive .env (secrets) generation, DNS check,
# ufw rules, hysteria config generation, compose up, waits for the
# Let's Encrypt certificate, prints the client URI.

set -euo pipefail

echo "=== verges bootstrap ==="

# --- preflight (before common.sh: .env may not exist yet) ---
if [ "$(id -u)" -ne 0 ]; then
	echo "ERROR: run as root (ssh root@<vps>)" >&2
	exit 1
fi
for cmd in docker git envsubst openssl ufw getent; do
	command -v "$cmd" >/dev/null 2>&1 || {
		echo "ERROR: '$cmd' not found." >&2
		case "$cmd" in
		envsubst) echo "  fix: apt-get update && apt-get install -y gettext-base" >&2 ;;
		docker) echo "  fix: curl -fsSL https://get.docker.com | sh" >&2 ;;
		esac
		exit 1
	}
done
docker compose version >/dev/null 2>&1 || {
	echo "ERROR: docker compose plugin missing" >&2
	exit 1
}
if ! systemctl is-enabled docker >/dev/null 2>&1; then
	echo "enabling docker at boot"
	systemctl enable docker
fi

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"
if [ "$REPO_DIR" != "/opt/verges" ]; then
	echo "NOTE: repo is at $REPO_DIR, convention is /opt/verges (continuing)"
fi

# --- interactive .env generation (idempotent: keeps an existing file) ---
if [ -f .env ]; then
	echo ".env already exists — keeping it"
else
	echo "generating .env (secrets)"
	read -r -p "ACME email for Let's Encrypt (SSL_EMAIL): " ssl_email
	[ -n "$ssl_email" ] || { echo "ERROR: email is required" >&2; exit 1; }
	case "$ssl_email" in
	*@*) ;; # rudimentary shape check
	*) echo "ERROR: that does not look like an email" >&2; exit 1 ;;
	esac
	read -r -p "Generate a random Hysteria2 password? [Y/n] " answer
	case "$answer" in
	n | N)
		read -r -p "Hysteria2 password (VERGES_PASSWORD): " verges_password
		;;
	*)
		verges_password="$(openssl rand -hex 24)"
		echo "generated password: $verges_password"
		;;
	esac
	[ -n "$verges_password" ] || { echo "ERROR: password is required" >&2; exit 1; }
	case "$verges_password" in
	*[!A-Za-z0-9_-]*)
		echo "WARN: password contains characters outside [A-Za-z0-9_-]; it may break shell sourcing or need URL percent-encoding" >&2
		read -r -p "Continue anyway? [y/N] " cont
		case "$cont" in y | Y) ;; *) exit 1 ;; esac
		;;
	esac
	{
		echo "# verges secrets — generated by scripts/bootstrap.sh $(date -u +%FT%TZ)"
		echo "SSL_EMAIL=${ssl_email}"
		echo "VERGES_PASSWORD=${verges_password}"
	} >.env
	chmod 600 .env
	echo "wrote .env (chmod 600)"
fi

# --- from here on, shared helpers (validates config.env and .env) ---
# shellcheck source=scripts/lib/common.sh
. "$REPO_DIR/scripts/lib/common.sh"

check_dns

# --- firewall ---
# NOTE: docker-published ports bypass ufw (docker's iptables rules run
# before ufw's). These rules document intent and protect the host level
# if that behavior ever changes. Never remove the SSH rule.
ufw allow 80/tcp >/dev/null                       # ACME HTTP-01 + redirect
ufw allow 443/tcp >/dev/null                      # HTTPS (caddy)
ufw allow "${VERGES_PORT}/udp" >/dev/null         # Hysteria2 main port
if [ -n "${VERGES_HOP_RANGE:-}" ]; then
	# ufw uses a colon for ranges (e.g. 20000:30000/udp).
	ufw allow "${VERGES_HOP_RANGE%-*}:${VERGES_HOP_RANGE#*-}/udp" >/dev/null # Hysteria2 port hopping range
fi
if [ "$FORWARD_ENABLED" -eq 1 ]; then
	ufw allow "${FORWARD_PORT}/tcp" >/dev/null     # gost TCP forward to indigenous (VLESS relay)
	ufw allow "${FORWARD_PORT}/udp" >/dev/null     # gost UDP forward to indigenous (hysteria2 relay)
fi
echo "ufw rules ensured: 80/tcp, 443/tcp, ${VERGES_PORT}/udp${VERGES_HOP_RANGE:+, ${VERGES_HOP_RANGE}/udp}${FORWARD_ENABLED:+, ${FORWARD_PORT}/tcp}"

# --- generate + start ---
gen_configs
compose up -d --remove-orphans
compose ps

# --- verify ---
if [ "$VERGES_ENABLED" -eq 1 ]; then
	wait_for_cert
fi
echo
echo "=== bootstrap done ==="
echo "site:       https://${VERGES_HOST}  (expect: 200 OK)"
if [ "$VERGES_ENABLED" -eq 1 ]; then
	echo "client URI:"
	client_uri
fi
if [ "$FORWARD_ENABLED" -eq 1 ]; then
	echo "VLESS+Reality relay entry: ${FORWARD_ENTRY} -> ${FORWARD_TARGET}"
fi
echo "logs:       scripts/logs.sh"
echo "status:     scripts/status.sh"
