#!/usr/bin/env bash
# One-time setup of the indigenous node (Debian/Ubuntu, run as root).
# Idempotent: re-running keeps existing .env secrets and data.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== indigenous-node bootstrap ==="

# --- preflight (before sourcing common.sh: .env may not exist yet) ---
if [ "$(id -u)" -ne 0 ]; then
	echo "ERROR: run as root" >&2
	exit 1
fi

for cmd in curl jq openssl envsubst systemctl ufw ss getent fallocate mkswap; do
	command -v "$cmd" >/dev/null 2>&1 || {
		echo "ERROR: '$cmd' not found." >&2
		case "$cmd" in
		jq) echo "  fix: apt-get update && apt-get install -y jq" >&2 ;;
		envsubst) echo "  fix: apt-get update && apt-get install -y gettext-base" >&2 ;;
		ss) echo "  fix: apt-get update && apt-get install -y iproute2" >&2 ;;
		fallocate|mkswap) echo "  fix: util-linux should be pre-installed" >&2 ;;
		esac
		exit 1
	}
done

# Ensure required packages are present.
apt-get update
apt-get install -y -q curl jq openssl gettext-base ufw git

# --- system tuning ---
SYSCTL_FILE="/etc/sysctl.d/99-indigenous-tuning.conf"
cat > "$SYSCTL_FILE" <<'EOF'
net.ipv4.tcp_congestion_control=bbr
net.core.default_qdisc=fq
net.ipv4.tcp_notsent_lowat=16384
EOF
sysctl --system

# Swap: only if enabled and enough free disk.
source config.env 2>/dev/null || true
SWAP_SIZE_MB="${SWAP_SIZE_MB:-256}"
if [ "$SWAP_SIZE_MB" -gt 0 ] && [ ! -f /swapfile ]; then
	free_mb="$(df -m / | awk 'NR==2 {print $4}')"
	if [ "$free_mb" -gt "$((SWAP_SIZE_MB + 300))" ]; then
		fallocate -l "${SWAP_SIZE_MB}M" /swapfile || dd if=/dev/zero of=/swapfile bs=1M count="$SWAP_SIZE_MB"
		chmod 600 /swapfile
		mkswap /swapfile
		swapon /swapfile
		echo '/swapfile none swap sw 0 0' >> /etc/fstab
		echo "vm.swappiness=10" >> "$SYSCTL_FILE"
		sysctl -w vm.swappiness=10
		echo "created ${SWAP_SIZE_MB}M swapfile"
	else
		echo "WARN: not enough disk for ${SWAP_SIZE_MB}M swap (free ${free_mb}M); skipping swap" >&2
	fi
fi

# Journald disk cap.
mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/99-indigenous.conf <<'EOF'
[Journal]
SystemMaxUse=100M
MaxFileSec=7day
EOF
systemctl restart systemd-journald || true

# --- generate .env idempotently ---
	if [ -f .env ]; then
		echo ".env already exists — keeping secrets"
		# migrate: add hysteria2 password if missing
		if ! grep -q '^HY2_PASSWORD=' .env; then
			echo "HY2_PASSWORD=$(openssl rand -hex 16)" >> .env
			chmod 600 .env
			echo "added HY2_PASSWORD to .env"
		fi
	else
		echo "generating .env secrets"
		PANEL_USER="admin"
		PANEL_PASS="$(openssl rand -hex 24)"
		{
			echo "# indigenous-node secrets — generated by bootstrap.sh $(date -u +%FT%TZ)"
			echo "XUI_PANEL_USERNAME=${PANEL_USER}"
			echo "XUI_PANEL_PASSWORD=${PANEL_PASS}"
			echo "XUI_API_TOKEN="
			echo "VLESS_UUID="
			echo "REALITY_PRIVATE_KEY="
			echo "REALITY_PUBLIC_KEY="
			echo "HY2_PASSWORD=$(openssl rand -hex 16)"
		} > .env
		chmod 600 .env
		echo "wrote .env (chmod 600)"
	fi

# --- source common.sh (validates envs) ---
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

# --- install 3x-ui ---
echo "installing 3x-ui ${XUI_VERSION} ..."
export XUI_NONINTERACTIVE=1
export XUI_DB_TYPE=sqlite
export XUI_ENABLE_FAIL2BAN=false
export XUI_USERNAME="${XUI_PANEL_USERNAME}"
export XUI_PASSWORD="${XUI_PANEL_PASSWORD}"
export XUI_PANEL_PORT="${XUI_PANEL_PORT}"
export XUI_WEB_BASE_PATH="${XUI_WEB_BASE_PATH}"

if ! bash <(curl -fsSL "https://raw.githubusercontent.com/MHSanaei/3x-ui/main/install.sh") "${XUI_VERSION}"; then
	echo "ERROR: official 3x-ui install script failed" >&2
	exit 1
fi

# --- configure 3x-ui memory/tuning via /etc/default/x-ui ---
cat > /etc/default/x-ui <<EOF
XUI_GOGC=50
XUI_MEMORY_LIMIT=192
XUI_MEMORY_RELEASE_INTERVAL=5
XUI_DB_CACHE_MB=8
XUI_DB_MMAP_MB=32
XUI_DB_JOURNAL_MODE=DELETE
XUI_LOG_LEVEL=warning
EOF

# Apply panel listen IP / base path / port / credentials.
/usr/local/x-ui/x-ui setting \
	-username "${XUI_PANEL_USERNAME}" \
	-password "${XUI_PANEL_PASSWORD}" \
	-port "${XUI_PANEL_PORT}" \
	-webBasePath "${XUI_WEB_BASE_PATH}" \
	-listenIP "${XUI_LISTEN_IP}"

systemctl restart x-ui

# --- wait for panel up ---
echo "waiting for 3x-ui panel ..."
for i in $(seq 1 60); do
	if curl -fsS "$(panel_url)/panel/api/inbounds/list" -H "Authorization: Bearer ${XUI_API_TOKEN:-invalid}" >/dev/null 2>&1 || \
	   curl -fsS "$(panel_url)/login" >/dev/null 2>&1; then
		break
	fi
	sleep 1
done

# --- mint API token if missing ---
if [ -z "$XUI_API_TOKEN" ]; then
	TOKEN_OUT="$(/usr/local/x-ui/x-ui setting -getApiToken -tokenName automation 2>/dev/null || true)"
	XUI_API_TOKEN="$(echo "$TOKEN_OUT" | awk '/apiToken:/{print $2}' | head -n1)"
	if [ -z "$XUI_API_TOKEN" ]; then
		# Retry after a short wait; the panel may still be initializing.
		sleep 3
		TOKEN_OUT="$(/usr/local/x-ui/x-ui setting -getApiToken -tokenName automation 2>/dev/null || true)"
		XUI_API_TOKEN="$(echo "$TOKEN_OUT" | awk '/apiToken:/{print $2}' | head -n1)"
	fi
fi

# --- generate UUID and Reality keys if missing ---
XRAY_BIN="$(xray_bin)"
if [ -z "$VLESS_UUID" ] && [ -n "$XRAY_BIN" ] && [ -x "$XRAY_BIN" ]; then
	VLESS_UUID="$($XRAY_BIN uuid)"
fi
if { [ -z "$REALITY_PRIVATE_KEY" ] || [ -z "$REALITY_PUBLIC_KEY" ]; } && [ -n "$XUI_API_TOKEN" ]; then
	KEYS_JSON="$(curl -fsS -H "Authorization: Bearer ${XUI_API_TOKEN}" "$(panel_url)/panel/api/server/getNewX25519Cert")"
	REALITY_PRIVATE_KEY="$(echo "$KEYS_JSON" | jq -r '.obj.privateKey')"
	REALITY_PUBLIC_KEY="$(echo "$KEYS_JSON" | jq -r '.obj.publicKey')"
fi

# Rewrite .env with generated values.
{
	echo "# indigenous-node secrets — generated by bootstrap.sh $(date -u +%FT%TZ)"
	echo "XUI_PANEL_USERNAME=${XUI_PANEL_USERNAME}"
	echo "XUI_PANEL_PASSWORD=${XUI_PANEL_PASSWORD}"
	echo "XUI_API_TOKEN=${XUI_API_TOKEN}"
	echo "VLESS_UUID=${VLESS_UUID}"
	echo "REALITY_PRIVATE_KEY=${REALITY_PRIVATE_KEY}"
	echo "REALITY_PUBLIC_KEY=${REALITY_PUBLIC_KEY}"
} > .env
chmod 600 .env
echo "updated .env with generated secrets"

# Re-source so the rest of the script sees the new values.
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

# --- verify Reality dest ---
echo "verifying Reality destination ${REALITY_DEST} ..."
if ! timeout 10 openssl s_client -connect "${REALITY_DEST}" -servername "${REALITY_SNI}" -tls1_3 </dev/null 2>/dev/null | grep -qi "protocol.*tlsv1.3"; then
	echo "WARN: Reality destination ${REALITY_DEST} did not respond with TLS 1.3. Continuing anyway." >&2
fi

# --- create/update inbound ---
./deploy.sh

# --- firewall ---
ufw default deny incoming >/dev/null 2>&1 || true
ufw allow 22/tcp comment 'SSH' >/dev/null
if [ "${DIRECT_INBOUND_ENABLE}" = "1" ]; then
	ufw allow "${DIRECT_VLESS_PORT}/tcp" comment 'VLESS+Reality direct' >/dev/null
fi
if [ "${RELAY_INBOUND_ENABLE}" = "1" ]; then
	ufw allow "${RELAY_VLESS_PORT}/tcp" comment 'VLESS+Reality relay (gost target)' >/dev/null
fi
# 3x-ui subscription server defaults to loopback; block it explicitly inbound just in case.
# ufw allow "${XUI_PANEL_PORT}/tcp" comment '3x-ui panel (loopback-only anyway)' >/dev/null
ufw --force enable

# --- systemd enable ---
cp "$SCRIPT_DIR/systemd/xui-backup.service" /etc/systemd/system/
cp "$SCRIPT_DIR/systemd/xui-backup.timer" /etc/systemd/system/
cp "$SCRIPT_DIR/systemd/hysteria2.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable x-ui
systemctl enable xui-backup.timer
systemctl start xui-backup.timer

# --- hysteria2 (QUIC) standalone server ---
install_hysteria() {
	local want="${HY2_VERSION#app/}"
	if [ -x /usr/local/bin/hysteria ] && /usr/local/bin/hysteria version 2>/dev/null | grep -q "${want}"; then
		return 0
	fi
	echo "installing hysteria ${HY2_VERSION} ..."
	local tmp
	tmp="$(mktemp -d)"
	curl -fsSL -o "${tmp}/hysteria" "https://github.com/apernet/hysteria/releases/download/${HY2_VERSION}/hysteria-linux-amd64"
	install -m 0755 "${tmp}/hysteria" /usr/local/bin/hysteria
	rm -rf "${tmp}"
}
install_hysteria

# self-signed ECDSA cert for hy2 (client pins/verifies via password; small + fast)
if [ ! -f "${HY2_CERT}" ] || [ ! -f "${HY2_KEY}" ]; then
	mkdir -p "$(dirname "${HY2_CERT}")"
	openssl ecparam -genkey -name prime256v1 -out "${HY2_KEY}"
	openssl req -x509 -new -key "${HY2_KEY}" -sha256 -days 3650 \
		-subj "/CN=${NODE_HOST}" \
		-addext "subjectAltName=DNS:${NODE_HOST}" \
		-out "${HY2_CERT}"
	chmod 600 "${HY2_KEY}"
	echo "generated hy2 self-signed cert for ${NODE_HOST}"
fi

ufw allow "${HY2_PORT}/udp" comment 'Hysteria2 QUIC' >/dev/null

# --- apt cleanup ---
apt-get clean

echo
echo "=== bootstrap done ==="
./status.sh
./client.sh
